- README.md
> fix Devoxx Morocco date

- README.md
Add two technical conferences.
> add the PCD & FrenchKit

- README.md
> add conference DataXDay

- README.md
a 1 day event happening at the same time in Berlin / Faro
> added Dev Day 19

- README.md
CloudBees Days, OW2Con, INFORSID, COMPAS, JHipster Conf, Agile en Seine
> Add misc conferences

- README.md
> Add Flutter Conf Paris

- README.md
j'étais venu voir pour MiXiT qui en fait est déjà à jour, j'ai vu une minuscule typo.
Merci pour ce repo très utile :heart:
> petite typo

- README.md
> feat: Newcrafts 2020 canceled

- README.md
Addition of the AFUP Day (May 15th)
> Update for May

- README.md
Update date and location (virtualized)
> Update Hack.Commit.Push event

- README.md
Oh my that thing hits hard, I just PRed confs that would have been already past. Good reminder that we're now in August, not June
> Some extra cancellations :s

- README.md
Adding Le Halloween des Speakers 2020 (October 26th-30th, 2020)
> Halloween des Speakers 2020

- README.md
Many thanks for this great list @scraly 👍
> feat: add MiXiT

- README.md
> feat: add GopherCon, WTF is SRE

- README.md
> feat: add GitOpsDays June 9-10

- README.md
Added following events: AlpesCraft, DevOpsCon, AnsibleFest, ApacheCon, Google Cloud Next, AWS re/invent, GOTO Amsterdam
> Add New events to calendar

- README.md
> Add Hashiconf Europe

- README.md
Signed-off-by: Rémi VERCHERE <remi.verchere@axians.com>
> Add SophiaConf

- README.md
- archives/2021.md
- Add Archilocus, French IT conf
- Move May conferences
> Add Archilocus and clean May

- README.md
Add "WTF is Cloud Native - Hybrid Conf" - Nov 4
> Add "WTF is Cloud Native - Hybrid Conf"

- README.md
> Add Monktoberfest

- README.md
> Add eBPF Summit

- README.md
> Add DevFest Perros-Guirec

- README.md
Adding .NET EDD + DeveloperWeek Global cloud conference
> Adding .NET EDD + DeveloperWeek Global cloud conference

- README.md
Adding Grafana ObservabilityCon
> Adding Grafana ObservabilityCon

- README.md
adding Jax London + Hack Conf 2021 + GopherCon UK + Agile Testing Days + Continuous Delivery
> add Jax London + Hack Conf 2021 + GopherCon UK + Agile Testing Days + Continuous Delivery

- README.md
Touraine Tech 2022 arrive :)
En physique, plein de bonne humeur, de tech et d'amitié ;)
> Ajout du lien pour Touraine Tech 2022

- README.md
Adding DevoxxFR 2022 based on twitter post : https://twitter.com/nmartignole/status/1443272489807880204
> Add DevoxxFR 2022 - 10th edition :tada:

- README.md
> :bento: add DevFest Nantes 2022

- README.md
Je me permets de te proposer les dates que j'avais déjà mises de côté pour ces confs :wink:
> 📆 feat: add some CFPs dates

- README.md
Online event about Datascience, AI and the following topics (in french) :
- Thème 1 : Récupération des données : Tracking, crawling, consolidation, parsing,...
- Thème 2 : Structuration des données : ETL, Indexation, Données Structurées, Data Management, Algorithme d'Apprentissage, Classification par Machine Learning...
- Thème 3 : Mise à disposition des données : Business Intelligence, Dashboard, KPI, Sécurisation, Haute Performance...
- Thème 4 : Analyse des données : Prévisions, statistiques, corrélations, Machine Learning,...
- Thème 5 : Recherche Opérationnelle : Planification, Optimisation, Aide à la Décision, Simulation, Algorithme, Yield, Revenue Management, Pricing
- Thème 6 : Intelligence Artificielle : Robotique, Réseaux de Neurones, Deep Reinforcement, Automatique, Chatbot...
> Add Dataquitaine online event

- README.md
Hi !
Just a simple commit to add Mobilis in Mobile :-)
Cheers !
Thomas
> feat: add Mobilis In Mobile

- README.md
SymfonyLive Paris 2022
SymfonyWorld Online 2022 Summer Edition
> Added 2 Symfony Conferences 😍

- README.md
Adding DevDays Europe April 2022
> Adding DevDays Europe

- README.md
Hello,
Here is the entry for next AlpesCraft edition 🙂 
Thanks for this great repo 👍
> feat: add AlpesCraft

- README.md
> 🗓️ CFP DevFest Lille 2022

- README.md
> feat: add codeurs en seine date

- README.md
j'ajoute le 1er évent français dédié aux APIs
> Add France API

- README.md
Adding CFP date and link to cdCon
> Adding CFP date and link to cdCon

- README.md
Le FIC est un évènement centré autour de la cybersécurité sous toutes ses formes et notamment les thèmes suivants :
- Du reverse engineering ;
- Des recherches en vulnérabilités ;
- Des analyses de malware ;
- Des attaques cryptographiques ;
- Des attaques physiques ;
- Des techniques issues de l’observation “terrain” (blue team, opérationnels…)…
> Add FIC 2022

- README.md
Just a minuscule error in the CFP link
(Many thanks for this repository, huge help)
> fix: CFP link for cloud sud

- README.md
Adding Some more confs : 
- SLOConf
- RailsConf22
- MSFT Build
> Adding SLOConf + RailsConf22 + MSFT Build

- README.md
Source MixIt : https://twitter.com/mixitconf/status/1488526469903044618
> Update MixIt CfP + FOSDEM (online edition)

- README.md
- archives/2022.md
I added in archive a 2022.md file, then I extracted January events to the archive.
hope it helps 😉
> Creating 2022 archive file + extracting january events

- README.md
Une de plus pour la route, autour de la cybersécurité
> Add THCon 2022

- README.md
> Add Closed Captions Label

- README.md
Add BaselOne22 conference in Basel
> Add BaselOne22

- README.md
> 🗓 feat: add BreizhCamp 2022

- README.md
* Add Cloud Ouest 2022 + cfp link
* switch Cloud Native Rejekts & Kubernetes Community Days Chennai 2022 cfp status to "red"
> chore: add CloudOuest 2022

- README.md
> Add ParisTestConf

- README.md
> Suggesting WeAreDevelopers in Berlin 14/15th june

- README.md
Signed-off-by: Rémi Verchère <r.verchere@linkbynet.com>
> feat: add devops-dday #7

- README.md
Hello Aurelie,
Addition of 2 conferences.
* Flosscon is a small conf about free software I organized with a friend.
It is located on Grenoble campus and is free for all.
* Openinfra is a major conference about "Openstack" world.
> Add Flosscon 2022 and Open Infra Summit 2022

- README.md
Petit nettoyage de printemps 😉
> doc: 📝 update for some closed CFP

- README.md
> doc: 🗓 add Bdx.io

- README.md
> doc: 🗓 add CFP date for Devoxx Morocco

- README.md
Add DevFest for Ukraine event on 14-15 of June 2022 
https://devfest.gdg.org.ua/
> Add DevFest for Ukraine

- README.md
Add DevOpsDays Bengaluru(India)
> add DevOpsDays Bengaluru

- README.md
Add Intersection Conference 2022 (Torino - Italy) to the list of conferences in the README.md.
> 🚀 add Intersection Conference 2022 link to README

- README.md
> Add JavaDay from Paris JUG

- README.md
One question: Should I also change badges from `archives/` directory?
> fix(README): Changed expired CFP badge color to  red

- README.md
adding https://eurorust.eu 
CFP: https://www.papercall.io/eurorust-2022
> add EuroRust

- README.md
Added GDG DevFest Craiova 2022 conference - September 24th
> Added GDG DevFest Craiova 2022 conference

- README.md
Signed-off-by: Mathieu Tortuyaux <mtortuyaux@microsoft.com>
<hr>
Hi, thanks! :)
> readme: add summercamp

- README.md
- archives/2022.md
* Adding SRE France - Summer Camp 2022
* Moving July to archive
* Expiring some CFPs
> Adding SRE France - Summer Camp 2022

- README.md
adding FlowCon data - no CFP link
> AddingFlowCon

- README.md
Add Arm DevSummit 2022 to the list.
> Add Arm DevSummit 2022

- README.md
> Add NDC London

- README.md
Pas forcément le salon le plus orienté "développeur" qui soit, mais un bon moyen de réseauter et de découvrir de nouveaux projets
> Add BigData & AI Paris 2022

- README.md
Added the best conference of the world 😇
> doc: 📝 Add TNT'23

- README.md
je viens enfin de retrouver cette page aujourd'hui (je la cherchais depuis des semaines). 
Bref, je propose de rajouter quelques conférences Agiles.
> feat: add ATM2022, ATN2022, Agile Grenoble 2022 and ATR2022

- README.md
> Voxxed Days Zurich CFP

- README.md
Thanks again for your awesome repo
> End date for Touraine Tech 2023 is November 27th, not December 4th

- README.md
> feat: kdc cfp for France is opened

- README.md
> Add AFUP Day 2023

- README.md
Add Hack It N cybersecurity conference
> Add Hack It N cybersecurity conference

- archives/2019.md
Another colon missing. This is for future works.
> fix(archive/2019): This one is left behind from yesterday commit

- README.md
Put red color for closed CFP 😉
> 📝 close ended CFP

- README.md
> Adding archilocus Bordeaux

- README.md
Adding few conferences in 2023
> Add few conferences

- README.md
From https://opsindev.news/archive/2022-12-16/#events-and-cfps Inspired by https://twitter.com/aurelievache/status/1603829191396425736
> Add events from opsindev.news newsletter

- README.md
> Added Microsoft 365 EduCon DC

- README.md
> Added ProductWorld 2023

- README.md
> Added Remix 2023

- README.md
> Added PowerShell Day UK 2023

- README.md
> Added CodeCampSDQ

- README.md
an offline event. Good name, good example for character escaping.
> Added php[tek]

- README.md
an online event via linkedin events
> Added CSI Linux Conference

- README.md
> Added TEQNation 2023

- README.md
> Ajout Salon de la data Nantes

- README.md
> Add VueJs Amsterdam

- README.md
Hello, we would like to add the dates for Devfest Lille 2023 🎉
> Add Devfest Lille 2023 and CFP dates

- README.md
- archives/2017.md
- archives/2018.md
- archives/2019.md
- archives/2020.md
- archives/2021.md
- archives/2022.md
Added dates for Riviera DEV 2023 (July 10-12th), and fixed a couple typos here and there.
CFP dates will be added soon.
> Added Riviera DEV 2023 + misc

- README.md
Add a new entry for [GopherCon UK](https://www.gophercon.co.uk).
Added a new line to the `README.md` file which is at the root of the repo.  
The CFP is not opened yet, therefore I haven't added any badge.
> ✨ adding GopherCon UK

- README.md
Found on https://foojay.io/calendar/.
> Add a bunch of java events

- README.md
Update title and link, add cfp.
> chore: Update JCON EUROPE 2023

- README.md
> chore: update FOSDEM link and location

- README.md
Added 3 event
FooConf
DevOps Pro Europe
OpenInfra Summit
> Added few events

- README.md
Add the DevTernity 2023 to the list.
> Add DevTernity

- README.md
Updade the color for closed CFP
> doc: 📝 put in red closed CFP

- README.md
> Add CppCon

- README.md
> Added PlatformCon 2023 to the June Conferences list

- README.md
- ElasticON Global
- Haystack US
- Craft Conference
> Add multiple events

- README.md
Adds Android Makers by droidcon 2023, the french Android conference.
> 📣 Adds Android Makers by droidcon 2023

- README.md
- fixed colors for some closed CFP;
- also, added location for Developer Week '23 (DWX) in Nuremberg, Germany (source = https://www.developer-week.de/en/location/#location);
> Fix closed CFP

- README.md
this commit also updates several closed CFP
> feat: add Full Stack Europe 2023

- README.md
hello @scraly for add this conference !
> Add conference OW 23

- README.md
> Infobip Shift

- README.md
Add the "Meeting C++" Conference in Berlin
> Add Meeting C++

- README.md
> Add conference Devoxx Morroco

- README.md
Adding a new French conference
> Add Lyon Craft conference

- README.md
Add Oredev and CFP for the conference
> Add Oredev and CFP for the conference

- README.md
Add all NCD conferences for 2023
> Add all NCD conferences for 2023

- README.md
Update color for some closed CFP 😉
> doc: 📝 put red on closed CFP

- README.md
> Add some events

- README.md
- (Add) WordCamp Switzerland
- (Add) WordPress Contributor Day Paris
- (Add) WordCamp Paris
- (Add) WordCamp Europe
> WordPress related conferences

- README.md
> Add codestantine

- README.md
Thanks for running this repo, @scraly! Addint DevOpsDays Seattle, which I am an organizer of.
> Adding DevOpsDays Seattle

- README.md
> Add CFP devBcn

- README.md
> Add Baselone 2023

- README.md
> add GCCD Kolkata, India 2023

- README.md
> doc: 📝 add Beer City Code

- README.md
> doc: 📝 add Breizh Camp 2023

- README.md
> doc: 📝 add DevRelCon London 2023

- README.md
add the CFP date for Breizh Camp
> doc: 📝 add Breizh Camp CFP

- README.md
> Ajout devfest Toulouse

- README.md
It was delayed by a week a few weeks ago.
> Voxxed Days Luxembourg's CFP ends tomorrow

- README.md
> Add ParisTestConf 2023

- README.md
> Add try! Swift NYC conference

- README.md
> Add MiXiT 2024

- README.md
> feat: Add React Day Berlin

- README.md
https://flutterconnection.io/
Thank you 👍
> Add Flutter Connection

- README.md
> feat: add TestJS Summit 2023

- README.md
> feat: add CDE Universe 2023

- README.md
> add KubeCon 2024 Paris

- page/src/components/CalendarGrid/CalendarGrid.js
- page/src/components/CalendarGrid/CalendarGrid.utils.js
- tools/mdParser.js
Integrate PR #436 into the new code organization
Thanks @Damien-VS! ❤️
> Fix: events not displayed even if the date is correct

- README.md
https://devfesttoulouse.fr/#le-cfp
> feat: add 2023 DevFest Toulouse CFP

- README.md
- Google Cloud Bali
- Global Azure Purwokerto
- SANS Community Night Jakarta
> Added 3 events

- README.md
https://www.developerweek.com/global/conference/cloud/
> feat: add DeveloperWeek Cloud

- README.md
See https://twitter.com/DevoxxMA/status/1651203308948684802
> fix: update Devoxx MA dates

- README.md
Add in July 7-9 Nante Maker Campus
> July Nantes Maker

- README.md
Add PhpCon Poland conference date
> Add PhpCon Poland

- README.md
https://developer.apple.com/wwdc23/
> feat: add WWDC23

- README.md
> feat: add Collision 2023

- README.md
> feat: Add GlueCon 2023

- README.md
> feat: add Open Core Summit 2023

- README.md
> chore: add Forum PHP CFP link + date

- README.md
> Add SRE France SummerCamp

- README.md
Request to update repo with Italian Agile Day 2023 - Italy
> Request to update repo with Italian Agile Day 2023 - Italy

- README.md
> Request to update repo with Cloud Native Summit 2023 -  New Zealand

- README.md
https://www.flutterfriends.dev/
> Add Flutter & Friends

- README.md
Added events with locations and Call for papers
> Add Droidcon events

- README.md
> feat: add Refactor DX 2023

- README.md
> feat: Add NODES 2023

- README.md
A conference only animated by womens to inspire and encourage.
> Add WHO run the Tech

- README.md
- added [apexdevsummit.com](https://www.apexdevsummit.com/)
- also fixed some typo for consistency
> feat: Add Apex - The XRPL Developer Summit

- README.md
Add Web Summit event in Lisbonn
> Add Web Summit 2023

- README.md
> Adding Euroku 2023

- README.md
Update - closed CFP for Italian Agile Day 2023 - add red color to img
> Update closed CFP for Italian Agile Day 2023

- README.md
> chore: add cdCon Japan Dec 23

- README.md
let me know if any other files need to be updated as well.
> add CppIndiaCon 2023 (#572)

- README.md
Hi 👋 
Adding missing CFP dates for ScalaIO and DevRelX 😃 
Thanks for the repo! 🥇
> Add ScalaIO and DevRelX CFP dates

- README.md
Adding GNOME.Asia Summit 2023: https://events.gnome.org/event/170/
> feat: add GNOME.Asia Summit 2023

- README.md
Added DevFest Stockholm 2023 and KCD Oslo 2024
> Added DevFest Stockholm 2023 and KCD Oslo 2024

- README.md
Please add our conference to your list
> Add Cloud Builders

- README.md
- archives/2018.md
Add Asynconf event 30-31 october 2023
> Adding Asynconf Event

- README.md
Saw [on LinkedIn that the CFP for the Aix-Marseille's Agile Tour got extended](https://www.linkedin.com/feed/update/urn:li:activity:7103273679081328640/).  
Also, did some cleanup of date colors.
> Cfp agile tour aix marseille

- README.md
> feat: Add Archilocus october 2023

- README.md
Also fix a lowercase "S" in "Sydney" for another conferece.
> Add Civo Navigate North America 2024

- README.md
Added our new event in The Netherlands with CFP
> Add KCD Utrecht 2023

- README.md
- Added code::dive conference in README.md.
> [HacktoberFest2023]:[dev-conf-agenda]: Added code::dive conference into the list

- README.md
The best tech conference ... ever
#TeamRillettes
> feat: Add Touraine Tech 2024 edition

- README.md
Add Go West Conf 2023 https://www.gowestconf.com/
I strangely did not find the CFP link or dates... 🤔
> feat: Add Go West Conf 2023

- README.md
* added Voxxed Days Cern date + cfp
* fixed Voxxed Days Ticino (19, not 20)
* added cfp for Ticino
> Add Voxxed CERN + cfp for Voxxed Ticino

- README.md
Hello! :) 
Team Rillettes au rapport !
> Add Touraine Tech CFP

- README.md
> feat: SyliusCon 2023

- README.md
> feat: Add GopherCon Singapore

- README.md
Added CfgtMgmtCamp with CFP Open
> Add CfgtMgmtCamp

- page/src/App.jsx
- page/src/app.reducer.js
- page/src/components/Day/Day.jsx
- page/src/components/EventDisplay/EventDisplay.jsx
- page/src/components/Filters/Filters.jsx
- page/src/components/ListView/ListView.jsx
- page/src/components/SelectedEvents/SelectedEvents.jsx
- page/src/utils.js
- tools/mdParser.js
> Adding closed captions filtering

- README.md
- archives/2017.md
- archives/2018.md
- archives/2019.md
- archives/2020.md
- archives/2021.md
- archives/2022.md
- archives/2023.md
- page/src/App.jsx
- page/src/components/Day/Day.jsx
- page/src/components/Filters/Filters.jsx
- page/src/components/ListView/ListView.jsx
- page/src/components/SelectedEvents/SelectedEvents.jsx
- page/src/styles/Filters.css
- page/src/utils.js
- tools/mdParser.js
This is a unification of how the country is formatted in the markdown and the code for allowing to filter by country.
> Adding city and country extraction and filter by country

- page/src/components/EventCount/EventCount.jsx
- page/src/components/SelectedEvents/SelectedEvents.jsx
> Adding the filtering to the events count

- page/src/App.jsx
> Showing the Download calendar button only when you are in the calendar view

- README.md
Dates extracted from the [TNT website](https://touraine.tech/)
> TouraineTech update

- README.md
Add Devfest Nantes event 17-19 october 2024
> Add devfest nantes

- CONTRIBUTING.md
Before becoming an index of all the meetups or promotional events. I think it's important to define the validation rules.
> Proposal to specify the type of conferences we wish to have

- README.md
I enjoy to start to think: how to do it with algorithms 👍
> 🔧 chore: update CFP badges (🟢->🔴)

- README.md
Add DevDay conference + CFP (28 march 2024)
> Add DevDay conference in Belgium

- README.md
Add 3 angular events:
- Angular Day
- NG Rome
- ng-India
> feat: add angular events

- README.md
Add JChampions Conference to the list .
Online event.
> Add Conference JChampions Conference

- README.md
CodeEurope is a developer conference that happens in Krakow, Poland - https://www.codeeurope.pl/en/
> Added CodeEurope Poland 2024

- README.md
Agile Game France 2024 sur Valence (Drôme)
> Ajout Agile Game France 2024

- README.md
Add JConf Dominicana conference
> Add JConf Dominicana conference

- README.md
> Change date DevDay 2024 mons

- README.md
CFP link to be advertised soon (January 22nd)
> Added Riviera DEV (08-10 July 2024)

- README.md
Adds an entry for Mobilis in Mobile :-)
Thanks Aurélie!
> feat: Add Mobilis In Mobile 2024

- README.md
First contribution I hope I followed correctly the guidelines. Thanke for creating this site
> Add Conference Rails World 2024

- page/src/app.hooks.js
- page/src/components/Filters/Filters.jsx
- page/src/misc/geolocations.json
- tools/mdParser.js
> Add scholarship filter

- README.md
Hello, 
Polycloud is on June 1st and not on June 2nd. :+1: 
Thanks in advance. :grin:
> Fix Polycloud date

- README.md
> Add GeeCon Poland

- page/index.html
- page/src/App.jsx
- page/src/components/YearSelector/YearSelector.jsx
- page/src/misc/geolocations.json
- page/src/routes/datepage.jsx
- page/src/routes/index.jsx
- page/src/routes/listpage.jsx
- page/src/routes/mappage.jsx
- page/src/routes/year.jsx
- page/src/styles/Filters.css
- page/src/styles/ViewSelector.css
- page/src/styles/YearSelector.css
- page/vite.config.js
|Before|After|
|--|--|
|![Screenshot 2024-02-09 051111](https://github.com/scraly/developers-conferences-agenda/assets/40712686/01e86dec-da06-464e-a0da-735498c99abd)|![image](https://github.com/scraly/developers-conferences-agenda/assets/40712686/1d9af34c-be9f-4962-b419-c19fe05b6b90)|
> Better Route Readability (Code Quality)

- README.md
Add Devoxx Poland and trim trailing whitespace
> Add Devoxx Poland and trim trailing whitespace

- README.md
This PR was generated via GH action
- Updates CFP status color green to red
- Generates geo locations
> Update CFP status color

- README.md
> Adding a few events

- README.md
> Add Devoxx Morocco CFP Link

- README.md
> Add VoxxedDays Thessaloniki

- scripts/README.md
- scripts/filterCFPs.gs
Add an utility script to display CFPs with some filters that can be used on Google Apps Script.
[Example of a Google App Script project](https://script.google.com/d/1bt680byslxMyruogvlkCucjfgcwX_FlEjEgEpp--2HCjp45dRbKCL93v/edit?usp=sharing) (read-only)
Example output:
<details>
<summary>Markdown style</summary>
|Name|🗓️ Dates|📍 Location|🗣️ CFP Status|
|---|---|---|---|
|[We Love Speed](https://www.welovespeed.com/)|17/9/2024|Nantes (France)|[🔴 Open until 26/5/2024](https://www.welovespeed.com/2024/cfp)|
|[Agile Tour Sophia-Antipolis 2024](https://www.telecom-valley.fr/agile-tour-sophia-2024/)|26/9/2024|Biot (France)|[🔴 Open until 31/5/2024](https://sessionize.com/agile-tour-sophia-antipolis-2024/)|
|[Agile Tour Rennes 2024](https://agiletour.agilerennes.org/)|13/11/2024 au …
> Add Google App Script script to send filtered opened CFPs to a chat service

- page/src/App.jsx
- page/src/components/Filters/Filters.jsx
- page/src/components/ShortDate/ShortDate.jsx
- page/src/components/ViewSelector/ViewSelector.jsx
- page/src/contexts/FilterContext.jsx
- page/src/styles/App.css
- page/src/styles/Filters.css
- page/src/styles/ListView.css
- page/vite.config.js
> feat: New Filter UI (No new list view commits)

- README.md
DevOps Rex is the official event name
> Rename DevopsDay Paris to DevOps Rex

- README.md
TNT25 (conference date ad CFP)
> feat: ✨ TNT25

- README.md
- page/src/misc/geolocations.json
> feat: add cfp for java land and codeur en seine

- README.md
> Adding QCon London

- README.md
- page/src/misc/geolocations.json
- Add a new conference named Tech Rocks Asia 2025
- Modify the geolocation name
> Add Tech Rocks Asia 2025

- README.md
- archives/2024.md
> Add App.js

- README.md
> Adding CfgMgmtCamp 2025

- README.md
> Add All Things Open 

- README.md
Updated readme.md --> added conference JCON OpenBlend Slovenia and CfP link
> Add Conference JCON OpenBlend Slovenia

- README.md
> Adding Container Days Hamburg

- README.md
> Remove DevOps D-Day 2025

- README.md
Add React Paris to conferences of 2025
> Add React Paris

- README.md
> Add BDX I/O 2025

- page/src/App.jsx
- page/src/components/CfpView/CfpView.jsx
- page/src/components/Filters/Filters.jsx
- page/src/components/ViewSelector/ViewSelector.jsx
- page/src/components/YearSelector/YearSelector.jsx
- page/src/routes/cfppage.jsx
- page/src/routes/datepage.jsx
- page/src/routes/listpage.jsx
- page/src/styles/CfpView.css
This Pull Request adds a new CFP view.
TODO:
> Add a CFP view

- README.md
- Change Nebraska.Code() 2025 CFP date from Jan 06 to Feb 01
> Update Nebraska.Code() 2025 CFP date

- page/package-lock.json
- page/package.json
- page/src/components/CfpView/CfpView.jsx
- page/src/styles/CfpView.css
In the CFP view, add an emoji flag for the country/location of an event.
> feat: add emoji for country in cfp view

- README.md
> Added two events

- page/index.html
- page/src/styles/App.css
Improve a little the footer.
Before:
After:
> Improve footer

- CONTRIBUTING.md
- page/.eslintrc.json
- page/.prettierrc
- page/eslint.config.js
- page/package-lock.json
- page/package.json
- run.sh
This repository is updated by several contributors so we need format and linters ;-)
Run linters: `npm run lint`
Run format: `npm run format`
> Add linters and format (Prettier and ESLint)

- README.md
> Added few events :)

- page/src/app.hooks.js
> Fix multi days conferences are reported only for starting and ending days, not during the whole duration

- README.md
> Add KCD Utrecht CFP link and expiry date

- README.md
Added Agile Testing Days 2025 CfP
> Added: Agile Testing Days 2025 CfP

- README.md
cf https://bsky.app/profile/devfesttoulouse.fr/post/3lkbzhmkjxf2u
> Add DevFest Toulouse 2025

- README.md
Positive Design Days, 12 Juin
BSides Mulhouse, 7 octobre
Devfest Strasbourg, 27 novembre
Merci :)
> Add Positive Design Days, BSides Mulhouse and Devfest Strasbourg

- meetups.md
Add some references to meetups / user groups:
- FinistDevs
- Code d'Armor
- GDG Rennes
- GDG Toulouse
- RennesJS
> Add more meetups and user groups

- page/src/components/YearSelector/YearSelector.jsx
This is the changes made when you run `npm run format`, just wanted to add it in a commit to main.
Thanks!
> Committing the linter fixes

- meetups.md
Quelques nouveaux meetups.
Ordre alphabétique: c'est pas le mieux, mais c'est un début.
Ce .md est à 90% aligné avec https://umap.openstreetmap.fr/en/map/meetups-france_1231721#6/47.078/3.296
> WIP: Add some additional meetups

- page/src/components/ListView/ListView.jsx
- page/src/styles/ListView.css
> Fixing list view for responsiveness

- TAGS.csv
This PR was generated via GH action
- Generates tags
> Generate Tags

- tools/mdValidator.js
I have added validator function in mdValidator.js to validate duplicate entries exist in TAGS.csv.
> [mdValidator] Check if there are duplication in TAGS.csv file #1579

- README.md
https://www.algolia.com/devcon
> Add Algolia DevCon 2025

- README.md
Added:
* RustLab 2025
* RustWeek 2026
* RustConf 2026
> Adding 3 Rust conferences
