scraly/developers-conferences-agenda

README.md
https://github.com/homeferences/list is growing rapidly, I thought it was a good idea to link both of them. WDYT?
=> Add homeconferences url to the readme

README.md
https://twitter.com/voxxed_lu/status/1263770037946630144
> Voxxed Days Luxembourg 2020 is now officially (not really a secret though) postponed to next year 😢
> We're pleased to announce Voxxed Days Luxembourg 2021 will take place on June the 21st and 22nd 2021!
> Read more here: https://luxembourg.voxxeddays.com/en/blog/voxxed-days-luxembourg-2020-cancelled/
=> Voxxed Days Luxembourg 2020 canceled

README.md
SnowCamp.io 2021 is cancelled
Hello,
It's with regret we announce that SnowCamp 2021 is cancelled. With the evolution of the Covid crisis, we think it's wiser to cancel the 2021 edition of SnowCamp.
Many thanks to the sponsors that were ready to support us for 2021 and to speakers that have already submitted great subjects!
If we can't see you on 2021, we hope to see you from the 2nd to the 5th of February for SnowCamp 2022!
Take care of yourself and your relatives! See you soon!
The SnowCamp.io Team.
PS: if you wish to support us as sponsors, you can contact us to team@snowcamp.io!
Source: [SnowCamp.io 2021 is cancelled](http://u8iw.mjt.lu/nl2/u8iw/miuo2.html?m=AMcAADW15hYAAcrK12gAALEKMxsAAAACR9wAJQJSAAW8XABfcZEL8gp_hQZMTcqKNJA6fL5FTAAFgFs&b=b6b9454d&e=aa386054&x=MFKt7YjejB4pAWf68a3h5FjA2 …
=> Snowcamp.io canceled

README.md
JBCNConf 2021 online edition will be held by the Barcelona Java User Group, related to JVM Technologies, microservices, and cloud technologies.
=> feat: add JBCNConf 2021 online edition

README.md
The collapsible extra infos are now working properly.
Initial problem comes from the use of lines break with HTML tags `<details>` and `<summary>`, which were badly rendered when followed by a new markdown list entry.
Easiest solution to this issue is to inline the whole list entry.
=> Update JChateau with working extra infos

README.md
Kubernetes Community Days Chennai 2022 is a two-day Virtual community event for Kubernetes and Cloud-native enthusiasts
=> Add Kubernetes Community Days Chennai 2022

README.md
I suggest adding 2 more conferences to come:  
- Serverless Architecture Conference 
-  API conference in April
Both are located the same days on the same place at The Hague (ND)
=> Adding Serverless Architecture Conference and API conference in April at The Hague (ND)

README.md
DevDays europe 2022 is online only now
=> DevDays europe 2022 is online only now

README.md
Mars@Hack est un évènement local dédié à la cybersécurité, avec 
- une compétition de type CTF accessible en local mais aussi à distance
- des conférences techniques et organisationnelle dédiées aux entreprises
=> Add Mars@Hack Event

README.md
Adding [DevOps World 2022](https://www.cloudbees.com/c/devops-world-2022-save-the-date) for Septembrer *(28-29)* + CFP until May 13
=> Add DevOps World 2022

README.md
Hello scraly
I just received an email from BDX I/O giving the CFP dates and links for 2022 edition
(Have fun at Le camping des speakers ;-p)
=> chore: add CFP for BDX IO 2022

README.md
Bonsoir Aurélie,
J'ajoute l'Agile Tour Lausanne 2022 qui aura lieu le 8 décembre 2022.
=> Added Agile Tour Lausanne Suisse 2022

README.md
CFP end date was moved to 13/11 : https://www.kcdfrance.fr/speakers
=> fix: KCD France CFP has been prolonged

README.md
Fix url kubecon. they change the url - remove -2023 at the end
Add conference FICEurope at Lille.
=> Change 2 conferences

README.md
There was only the closing `</a>` tag.
AFUP Day have multiple CFP links, so using the conference link as the CFP link.
=> fix: AFUP Day CFP

README.md
It was removed with the HashiTalks edition in https://github.com/scraly/developers-conferences-agenda/commit/b9c411ed1fbc5467d9a7b7cc172a127cb8a2b385
related to: https://github.com/scraly/developers-conferences-agenda/pull/275
=> Add PyConFr CFP

README.md
T-DOSE is a freely accessible open source event in the south of the Netherlands (Geldrop, near Eindhoven).
=> Add T-DOSE

tools/parser.py
Diff between old json and new json (timezone = Europe/Paris) :
```json
--- oldf.json	2023-01-05 22:00:58.083757282 +0100
+++ newf.json	2023-01-05 22:01:03.043911122 +0100
@@ -853,7 +853,7 @@
"name": "Elastic{ON}",
"date": [
1519686000,
-      1517439601
+      1519858801
],
"hyperlink": "https://www.elastic.co/elasticon/conf/2018/sf",
"location": "USA (San Francisco)",
@@ -1363,7 +1363,7 @@
"name": "Gopher Con Iceland",
"date": [
1527717600,
-      1525298401
+      1527976801
],
"hyperlink": "https://gophercon.is/",
"location": "Iceland",
@@ -1603,7 +1603,7 @@
"name": "La nuit du Hack",
"date": [
1530309600,
-      1527804001
+      1530396001
],
"hyperlink": "https://www.nuitduhack.com/fr",
"location": "France (Paris)",
@@ -2253,7 +2253,7 @@
"name": "DockerCon 2019",
"date": [ …
```
=> Fix end date computation in parser.py (fixes #319)

README.md
KubeHuddle is a community conference where Developers, Platform Engineers, DevOps, SRE, Cloud Enthusiasts, Technical and Business Strategists come together to learn from each other, collaborate and, innovate.
This conference will cover topics on:
Cloud technologies
Cloud Native and Kubernetes
Edge Computing
Platform Engineering
Technical Strategy
Real life production stories
Learning Cloud
The humanity and empathy side of tech.
KubeHuddle will happen in Toronto, Ontario, Canada in May 2023 🇨🇦
=> Added KubeHuddle Toronto 2023

README.md
- Open Source Day 2023, Florence, Italy
- Localization for Developer Week (15-17/02) - Source: https://www.developerweek.com/
- `img` for SymfonyLive Paris.
=> Added Open Source Day 2023

README.md, archives/2023.md
* Remove February 2023
* Add VoxxedDays Luxembourg CFP dates and link
* Remove trailing "#" in "weAreDevelopers World Congress" line
=> chore: add voxxeddays luxembourg cfp + cleanup

README.md
Perl and Raku are great programming languages and this year's conference will be in July in Toronto.
=> add The Perl and Raku Conference 2023

README.md
Koha is a conference written in Perl. This conference combines the two former conferences YAPC::Europe (Yet another Perl conference) and KohaCon...
=> Add Perl and Koha conference 2023

archives/2023.md
Hi,
thanks for this nice calendar.
This PR add the German Perl and Raku Workshop, that took place in February this year in Frankfurt (Germany).
Kind regards
Renée
=> Add German Perl and Raku Workshop 2023

page/src/styles/Calendar.css
The .date.intensity-4 text color vs. its background color is failing WCAG 2 contrast standards. Removing the color property fixes this.
Testing source: [webaim.org](https://webaim.org/resources/contrastchecker/)
❌ Fail
====
✅ Pass
====
=> Adjust .intensity-4 text color

.github/workflows/ghpages.yml, page/.gitignore, page/src/App.js, page/src/styles/App.css, page/src/utils.js, run.sh, tools/generateIcs.js
Add a build script to generate ICS files (one per year) at build time containing all events.
To test it : 
```shell
cd page
npm install -D --force
cd ../tools
node mdValidator.js
node mdParser.js
node generateIcs.js
cd ../page
npm run build
cd build
cp ../src/misc/*.ics .
npx serve
```
Note : I don't know React enough to make generated ICS files work in development mode (as it is located in a different folder), however, it seems to be working when building production assets, as described above. If you have any hints on what is missing, I'd appreciate some feedback :)
=> feat: publish ics as static ressources

tools/generateIcs.js
Update the script to fix dates in ICS files. If we look at the currently generated dates, they are invalid. 
```ics
DTSTART:549730221T000000
DTEND:NaNNaNNaNTNaNNaNNaN
```
I've also added a control to include dtend attribute only if their is a end date in the JSON file.
=> fix: update dates with valid values

README.md
The Agile Tour Bordeaux CFP is now open, until end of July.
=> Add atbdx cfp

README.md
I see no reference to a 2023 edition on the conf website, only 2024. So I suppose that 2023 edition was postponed to 2024
=> fix: update devworld conference dates

README.md
T-DOSE is a freely accessible open source event in the south of the Netherlands (Geldrop, near Eindhoven).
=> Add T-DOSE 2024

README.md
* 🔗 Link to DDD Europe 2024 added in [2024](https://github.com/scraly/developers-conferences-agenda#2024) section added
* 🗓️ Link to corresponding CFP + deadline badge added
* ✅ No warning for this new entry when running `$>cd tools && node mdValidator.js;`
=> feat: add DDD Europe 2024 with CFP

page/src/App.jsx, page/src/components/EventCount/EventCount.jsx, page/src/components/SelectedEvents/SelectedEvents.jsx, page/src/components/YearSelector/YearSelector.jsx, page/src/styles/SelectedEvents.css, page/src/utils.js
Result of contributing session with @Farsen976 
* Added a `<EventCount />` component that take a list of events
* adjust label to 0, 1 or more events
* Updated `<SelectedEvents>` and `<YearSelector>` to use `<EventCount/>`
[event count.webm](https://github.com/scraly/developers-conferences-agenda/assets/1212392/2262973f-cf6c-40f0-a8c2-b2ee117a06cf)
=> feat: add event cont for day, month and year

.github/workflows/ghpages.yml, page/.gitignore, page/index.html, run.sh, tools/.gitignore, tools/generateRSS.js, tools/package-lock.json, tools/package.json
Hi,
In this PR, we add RSS support to the agenda. It allows users to subscribe to the RSS feed from a RSS client (Slack, browser extension, etc.) using this URL: https://developers.events/feed-events.xml
Feed is generated in the CI from the `all-events.json` list previously generated. While I locally tested the feed generation + reading from a local client, I did not tested the CI part.
=> provide JSON and ATOM rss feeds

README.md
We have 30 days left for CFPs
An online event hosted on YouTube for the community by the community, we have some great sessions submitted so far.
=> adding 90daysofdevops event

README.md
Hi @scraly! As promised I add these two conferences! 🎉
=> feat: add fluttercon and droidcon july 2024 in berlin

tools/generateRSS.js
This is still not working for me in feedly (I don't know why, I don't have a proper error), but other feeds agregators are working and the W3C validator is no longer complaining.
This aims to fix the #620 but something is not working with feedly
=> Fixing all the W3C feed validator errors

tools/generateIcs.js
Instead of having a 24H event when you import in your calendar (which is ugly),
we can have full day event instead.
It now looks like this:
=> Makes conferences looking like a fullday event

page/src/misc/geolocations.json, tools/geoCodes.js
This is more a proposal, so feel free to discard it if you don't see the value.
The whole point of this is to make it easy to track what is going on whenever we generate the geolocations again. What entries are added, to be able to check that directly in the diff.
The current format is a bit hard to read, and it's not easy to see what is going on.
=> Generate the goelocations files in a more readable format

run.sh, tools/README.md, tools/generateIcs4OpenedCfps.js
Reads the `page/src/misc/all-cfps.json` file and generates a `developer-conference-opened-cfps.ics` file. People can then subscribe to https://developers.events/developer-conference-opened-cfps.ics to know when CFPs are closing.
Note that the generated calendar only includes CFPs which are not yet closed when the script is running.
```sh
node generateIcs4OpenedCfps.js
```
```ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:DCA
BEGIN:VEVENT
UID:DevFest Jalingo 2023@dca-2023
DTSTAMP:20231019T114828
DTSTART:20231020
LOCATION:Jalingo (Nigeria)
SUMMARY:DevFest Jalingo 2023
URL:https://sessionize.com/devfest-2023-jalingo/
END:VEVENT
END:VCALENDAR
```
Not yet 😉
=> Add generateIcs4OpenedCfps.js

tools/generateRSS.js
Change 
```
atom: "https://developers.events/feed-events.atom"
```
to
```
atom: "https://developers.events/feed-events.xml"
```
to try to fix import on feedly
=> Try to fix ATOM feed import on feedly

README.md, page/src/App.jsx, page/src/misc/geolocations.json, page/src/styles/App.css
It's the next step for #677 (@dadoonet ) :-)
I displayed the "open CFP" button but currently the two buttons are displayed line after line:
I want to display them aside.
@gouz or @jespino , can you help me to display the two buttons next to each other? ☺️
=> Add opened CFP button

README.md
Their website is not yet updated but the CFP redirects to it anyway.
=> feat: Add GopherCon Brazil 2024

tools/generateIcs.js
When we have a multi-days event, we need to set the end date to be the day after.
Otherwise, the end date is considered at the very first hour of the day which makes the last day not part of the event.
See https://github.com/scraly/developers-conferences-agenda/pull/672#issuecomment-1775600800
In the following picture, we can see the fix (in green) vs the previous version (in blue).
=> Fix end date for multi days events

page/src/App.jsx
The routing was working great locally, but is broken on published pages, because if you refresh the page, the server returns a 404. This is because the server is not configured to return the index.html file for all routes.
This PR fixes that by using the HashRouter instead of the BrowserRouter.
=> Fixing the router on published pages

README.md
No CFP for this type of conference.
StaffPlus London URL
=> Add socrates rennes 2024

README.md
KCD Munich dates had an error. The CFP closed on March 31st and not January
=> Fix KCD Munich CFP dates

README.md
Vast majority of conference dates are written without leading zeros. This PR fixes a few dates that had them.
=> Unify dates by removing leading zeros

README.md
Add numerous DevOpsDays 🧠⚙️ conferences, and correct a handful that were already listed.
Source: https://devopsdays.org/
=> Add numerous DevOpsDays conferences

README.md
Adding the DevSecCon 2024 event and CFP to the repo per the contributing instructions.
=> Add DevSecCon 2024

README.md
This PR adds the FOSDEM conference (https://fosdem.org/2025/)
As of now, there is no Call for Papers (CFP) available yet, a Call for Devroom is currently opened. The CFP will be released later, once the devrooms are defined.
=> Add FOSDEM 2025

README.md
This is a fully volunteer-based unconference. There is no formal CFP, as anyone can propose a talk at the start of each day.
=> Add SoCraTes Germany 2025

page/src/app.hooks.js, page/src/components/CalendarGrid/CalendarGrid.jsx
Multiday conferences that span two months are shown when the end day in the start month is selected, e.g. YYC DataCon 2025 Feb 27 - Mar 1 is shown when Feb 1 is selected.
Before:
After:
=> Fix multiday conferences showing in wrong month

README.md
Hello, je tente l'ajout de la conf Agiletour Nantais 2025 dans le README.md, j'espère ne rien avoir cassé.
Je l'ai mis juste après l'Agiletour Bordeaux (qui est aux mêmes dates).
=> Ajout Agiletour Nantais 2025

README.md
This PR:
* Updates the website for CloudCon Sydney
* Adds the CFP link for CloudCon Sydney
=> Update website + CFP link for CloudCon Sydney
